base_url = "https://mlaveaux.github.io/"
title = "Home"
theme = "linkita"
compile_sass = true
build_search_index = true

[extra]
header_menu_name = "header_links"

[extra.profiles.mlaveaux]
avatar_url = "Laveaux_Maurice_MCS_PROM_PO_AS_3952.png"
social  = [
  { name = "github", href = "https://github.com/mlaveaux" },
  { name = "email", href = "mailto:mauricelaveaux@gmail.com" },
]

# Enable comments
comment = false
# Enable KaTeX support
math = false
# Enable Mermaid support
mermaid = false

# Menus
[extra.menus]
header_links = [
  { url = "@/projects/_index.md", name = "Projects" },
  { url = "@/cv/cv.md", name = "CV" },
]
